[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
somnia_testnet = "https://api.infra.testnet.somnia.network/"

[etherscan]
somnia_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://shannon-explorer.somnia.network/api" }